# Generated by Django 4.2.7 on 2024-06-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('roast', models.CharField(choices=[('light', 'light'), ('medium', 'medium'), ('dark', 'dark')], max_length=20)),
                ('size', models.CharField(choices=[('12', '12oz'), ('16', '16oz'), ('32', '32oz')], max_length=3)),
                ('coffee_type', models.CharField(choices=[('decaf', 'decaffeinated'), ('easy-late', 'easy-late'), ('flavored', 'flavored'), ('ground', 'ground'), ('organic', 'organic'), ('reserved', 'reserved'), ('seasonal', 'seasonal'), ('whole-bean', 'whole bean')], max_length=20)),
                ('price', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
