# Generated by Django 4.2.7 on 2024-06-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_type', models.CharField(choices=[('decaf', 'decaffeinated'), ('easy-late', 'easy-late'), ('flavored', 'flavored'), ('ground', 'ground'), ('organic', 'organic'), ('reserved', 'reserved'), ('seasonal', 'seasonal'), ('whole-bean', 'whole bean')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='coffee_type',
        ),
        migrations.AddField(
            model_name='product',
            name='coffee_type',
            field=models.ManyToManyField(to='product.coffeetype'),
        ),
    ]
