# Generated by Django 4.2.7 on 2024-06-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_coffeetype_remove_product_coffee_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roast', models.CharField(choices=[('light', 'light'), ('medium', 'medium'), ('dark', 'dark')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('12', '12oz'), ('16', '16oz'), ('32', '32oz')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='roast',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='roast',
            field=models.ManyToManyField(to='product.roast'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='product.size'),
        ),
    ]
