# Generated by Django 4.2.7 on 2024-06-23 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('public', 'public'), ('private', 'private'), ('friends', 'friends')], max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=3000)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('likes', models.IntegerField()),
                ('comments', models.CharField(max_length=3000)),
                ('shares', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
            ],
        ),
    ]
