# Generated by Django 4.2.7 on 2024-06-18 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('public', 'public'), ('private', 'private'), ('friends', 'friends')], max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=3000)),
                ('image', models.ImageField(upload_to='images/')),
                ('likes', models.IntegerField()),
                ('comments', models.CharField(max_length=3000)),
                ('shares', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
